name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Pack
        run: |
          dotnet pack src/DynamicQuery.AspNetCore/DynamicQuery.AspNetCore.csproj -c Release -o ./artifacts
          dotnet pack src/DynamicQuery.NetFramework/DynamicQuery.NetFramework.csproj -c Release -o ./artifacts

      - name: Publish to NuGet
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
